### ISSUE TITLE
this doesn't deal with function names, classes name and global variable name

### ISSUE THREAD

**Issue by mebjas** [wistful/SublimeAutoPEP8#37]
like mentioned in https://www.python.org/dev/peps/pep-0008/#function-names , the package doesn't take care of that?

**Comment by wistful** [comment]
SublimeAutoPep8 plugin uses [autopep8](https://github.com/hhatto/autopep8) module to format code.
I guess autopep8 doesn't do this because renaming functions and classes is rather refactoring than formatting and it's too dangerous.
Anyway, you can ask [autopep8](https://github.com/hhatto/autopep8) authors about this feature.
