### ISSUE TITLE
unable to edit default settings 

### ISSUE THREAD

**Issue by rdgao** [wistful/SublimeAutoPEP8#51]
this might be a really dumb question so apologies in advance:

in trying to change some settings for AutoPEP8, I navigated to the default settings file:

![image](https://user-images.githubusercontent.com/7810219/30932992-126bf2ca-a37e-11e7-865c-6353bfe97f6c.png)

however, on saving that file,  this error message pops up: 
![image](https://user-images.githubusercontent.com/7810219/30933038-2fb105f0-a37e-11e7-89d9-dd9d60a967ee.png)

I have also tried adding a user settings file under ST3/Packages/User, but that does not seem to do anything. What is the correct way of changing lint settings, e.g. max line length?

**Comment by rdgao** [comment]
i should also add that the default settings file does not allow for editing, in addition to not being able to find/save it.

**Comment by wistful** [comment]
Default settings aren't editable by design.
However, one should be able to change user settings.
The path from screenshot **${packages}/AutoPEP8/AutoPep8.sublime-settings** is not used anymore:
it [was changed ](https://github.com/wistful/SublimeAutoPEP8/commit/65b20cb612eb9ff346f934baccf2b5d0e2d5de6e#diff-04b587f94a8b347256e62b74e4b5220c) to **${packages}/User/AutoPep8.sublime-settings** two years ago.
Perhaps reinstalling plugin will help.
Current version is **1.3.6**.

**Comment by rdgao** [comment]
I've placed the settings file in the above directory and things are as expected now. Thank you!
